# Meta Data for SEO

## Homepage
title = "Open Component Model"
titleSeparator = "|"
titleAddition = "OCM"
description = ""
leader = "An open standard to describe software artifact delivery."
leader_open_source_text = "Open-source Apache-2.0 Licensed."
latest_version = "v0.6.0"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = []
ogLocale = "en_US"
domainTLD = "ocm.software.dev"
titleHome = "Open Component Model"

## Twitter Cards
twitterSite = ""
twitterCreator = ""

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "OCM"
schemaAuthor = ""
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = ""
schemaLocale = "en-US"
schemaLogo = ""
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = ""
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/open-component-model"
schemaSection = ""

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = '<small>© Copyright 2024, SAP SE and Open Component Model Contributors | <a href="/privacy-policy/">Privacy Policy</a> | <a href="https://www.sap.com/corporate/en/legal/terms-of-use.html">Terms of Use</a> | <a href="/legal">Legal</a></small>'

# Feed
copyRight = "© Copyright 2024, SAP SE and Open Component Model Contributors"

# Alert
alert = false
alertDismissable = true
alertText = ""

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/open-component-model/ocm-website"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = true
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
