[build.environment]
  NODE_VERSION = "25.5.0"
  NPM_VERSION = "11.8.0"
  HUGO_VERSION = "0.155.0"
  HUGO_EXTENDED = "true"

[build]
  ignore = "exit 1"

[context.deploy-preview]
  command = "npm run build -- --baseURL=$DEPLOY_PRIME_URL"
  publish = "public"

[context.production]
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    baseUrl = "https://doks.netlify.app/"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "yandex"
    ]
