[build.environment]
  NODE_VERSION = "22.12.0"
  NPM_VERSION = "10.9.2"
  HUGO_VERSION = "0.155.0"
  HUGO_EXTENDED = "true"

[build]
  ignore = "exit 1"

[context.deploy-preview]
  command = "npm run build -- --baseURL=$DEPLOY_PRIME_URL"
  publish = "public"

[context.production]
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    baseUrl = "https://doks.netlify.app/"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "yandex"
    ]

# Redirects for versioned paths
[[redirects]]
  from = "/dev/*"
  to = "/dev/:splat"
  status = 200

[[redirects]]
  from = "/current/*"
  to = "/current/:splat"
  status = 200

[[redirects]]
  from = "/v*/*"
  to = "/v:version/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200