#yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/refs/heads/main/schema/markdownlint-cli2-config-schema.json
ignores:
  - "content_versioned/version-legacy/**"
config:
  default: true
  MD001: false #Heading style - Allow heading levels to be incremented by multiple levels at a time
  MD004: false #Unordered list style
  MD009: false #no-trailing-spaces Trailing spaces
  MD013: false #Line length - https://github.com/DavidAnson/markdownlint/blob/HEAD/doc/Rules.md#md013
  MD024:
    siblings_only: true #Multiple headers with the same content
  MD031: false #Fenced code blocks should be surrounded by blank lines
  MD033: false #Inline HTML - https://github.com/DavidAnson/markdownlint/blob/HEAD/doc/Rules.md#md033
  MD036: false #No emphasis added
  MD059: false #Link text should be descriptive - https://github.com/DavidAnson/markdownlint/blob/main/doc/md059.md
