[[main]]
  name = "Docs"
  url = "/docs/"
  weight = 10

[[main]]
  name = "Community"
  url = "/community/engagement"
  weight = 20

[[main]]
  name = "Roadmap"
  url = "https://github.com/orgs/open-component-model/projects/10/views/5"
  weight = 30

[[social]]
  name = "GitHub"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-github" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path></svg>'
  url = "https://github.com/open-component-model"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Slack"
  pre = "<svg role=\"img\" width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"#fff\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M5.042 15.165a2.528 2.528.0 01-2.52 2.523A2.528 2.528.0 010 15.165a2.527 2.527.0 012.522-2.52h2.52v2.52zm1.271.0a2.527 2.527.0 012.521-2.52 2.527 2.527.0 012.521 2.52v6.313A2.528 2.528.0 018.834 24a2.528 2.528.0 01-2.521-2.522v-6.313zM8.834 5.042a2.528 2.528.0 01-2.521-2.52A2.528 2.528.0 018.834.0a2.528 2.528.0 012.521 2.522v2.52H8.834zm0 1.271a2.528 2.528.0 012.521 2.521 2.528 2.528.0 01-2.521 2.521H2.522A2.528 2.528.0 010 8.834a2.528 2.528.0 012.522-2.521h6.312zM18.956 8.834a2.528 2.528.0 012.522-2.521A2.528 2.528.0 0124 8.834a2.528 2.528.0 01-2.522 2.521h-2.522V8.834zm-1.268.0a2.528 2.528.0 01-2.523 2.521 2.527 2.527.0 01-2.52-2.521V2.522A2.527 2.527.0 0115.165.0a2.528 2.528.0 012.523 2.522v6.312zM15.165 18.956a2.528 2.528.0 012.523 2.522A2.528 2.528.0 0115.165 24a2.527 2.527.0 01-2.52-2.522v-2.522h2.52zm0-1.268a2.527 2.527.0 01-2.52-2.523 2.526 2.526.0 012.52-2.52h6.313A2.527 2.527.0 0124 15.165a2.528 2.528.0 01-2.522 2.523h-6.313z\"></path></svg>"
  url = "https://kubernetes.slack.com/archives/C05UWBE8R1D"
  weight = 20

