[[main]]
  name = "Docs"
  url = "/docs/overview/context"
  weight = 10

[[main]]
  name = "Spec"
  weight = 20
  identifier = "specification"
  url = "/spec/"

[[main]]
  name = "Project"
  url = "/project/about"
  weight = 30

[[main]]
  name = "Community"
  url = "/community"
  weight = 40

# [[main]]
#   name = "Blog"
#   url = "/blog/"
#   weight = 40

[[social]]
  name = "GitHub"
  url = "https://github.com/open-component-model"
  post = "v0.1.0"
  weight = 0

[[social]]
  name = "Slack"
  url = "https://kubernetes.slack.com/archives/C05UWBE8R1D"
  weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10

